Cruise Fleet : Add reserve form
ahmidou09/cruise-fleet-frontend pull request #8
Opened 2024-01-03 00:39 UTC by ahmed025566

Hello there, Teammates.
Hope you are doing well.

In this branch you could see I have done the following:

I have attached images to the item data table so that in the future the user can upload a photo for item.
I have adjusted the data base in backend to achieve attaching the images but accedintely pushed to dev and I have adjusted the route for creating a reservation.
I have created the reservation form: user will see the available cars to reserve  and when he click on any car it will created a border around it to tell the user it is selected and it will be selected to be sent to the server and I have added the other field and made all of them required.

2024-01-03 15:50 UTC, ahmidou09 requested changes
Status: CHANGES REQUIRED ♻️
Hi @ahmed025566 ,
Good job so far!
There are some issues that you still need to work on to go to the next project.

Highlights
✔️ Linters passing
✔️ Correct GitFlow

Required Changes ♻️
Check the comments under the review.

2024-01-03 15:50 UTC, ahmidou09 commented on src/components/pages/Car/CarsList.jsx
> +                <img src={images[index]} alt={car.name} />
the images prop in the CarsList component is marked as required but its value is undefined.
<img width="1274" alt="1" src="https://github.com/ahmidou09/cruise-fleet-frontend/assets/122125958/fe20de03-82d5-400b-aa44-c7b4d790bc91">

2024-01-04 01:34 UTC, Armynerh requested changes
Status: CHANGES REQUIRED ♻️
Hi @ahmed025566 ,
Good job so far!
There are some issues that you still need to work on to go to the next project.

Highlights
- All Linters are passing 
-  Correct GitFlow

Required Changes ♻️
Check the comments under the review.

2024-01-04 01:34 UTC, Armynerh commented on src/components/pages/Reservations/ReserveForm.jsx
> +                <img src={images[index]} alt={car.name} data-id={car.id} />
In addition to the changes suggested by @ahmidou09 , please review the reservation form so that the images can load properly.
change : 

`<img src={images[index]} alt={car.name} data-id={car.id} />`

to :
`<img src={car.photo} alt={car.name} data-id={car.id} />`

2024-01-04 01:34 UTC, Armynerh commented on src/components/pages/Reservations/ReserveForm.jsx
> +
- There is an issue with the select function, such that it allows you to select multiple elements and items on the page.

- I also suggest that you fix the page to inform the user if the reservation is successful or not and either render a new form on success or flash the error message on the screen.


https://github.com/ahmidou09/cruise-fleet-frontend/assets/88312845/897c1018-18cc-42ab-9230-d966a4429fe8

2024-01-04 13:35 UTC, alexansaa requested changes
Please, check the changes required by your peers

2024-01-05 00:53 UTC, merged